module.exports = {
    switchState: require('./television/sfr.switchState'),
    pause : require('./television/sfr.playPause'),
	play : require('./television/sfr.playPause'),
	rewind : require('./television/sfr.rewind'),
    fastForward : require('./television/sfr.fastForward'),
    programMinus : require('./television/sfr.programMinus'),
    programPlus : require('./television/sfr.programPlus'),
    programVod : require('./television/sfr.programVod'),
    volumeUp : require('./television/sfr.volumeUp.js'),
    volumeDown : require('./television/sfr.volumeDown.js'),
    setMuted : require('./television/sfr.setMuted'),
    setChannel : require('./television/sfr.setChannel'),
    pressKey : require('./television/sfr.pressKey'),
    openMenu : require('./television/sfr.openMenu'),
    openInfo : require('./television/sfr.openInfo'),
    rec : require('./television/sfr.rec'),
    yellowButton : require('./television/sfr.yellowButton'),
    greenButton : require('./television/sfr.greenButton'),
    blueButton : require('./television/sfr.blueButton'),
    rednButton : require('./television/sfr.redButton'),
};
